services:
  - type: web
    plan: free
    name: nkounkou-merveil
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn portfolio_project.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_project.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "portfolio-site.onrender.com"
