# Generated by Django 5.2.3 on 2025-07-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('whatsapp', models.CharField(blank=True, help_text='Numéro avec indicatif pays (ex: +242123456789)', max_length=20, verbose_name='WhatsApp')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('cv_file', models.FileField(blank=True, help_text='Fichier PDF du CV à télécharger', upload_to='cv/', verbose_name='CV (PDF)')),
                ('afficher_sidebar', models.BooleanField(default=True, verbose_name='Afficher la sidebar de contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Information de contact',
                'verbose_name_plural': 'Informations de contact',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(default='Portfolio', max_length=100, verbose_name='Nom du site')),
                ('description_site', models.TextField(default='Portfolio professionnel', verbose_name='Description du site')),
                ('favicon', models.ImageField(blank=True, help_text='Image 32x32px ou 16x16px', upload_to='site/', verbose_name='Favicon')),
                ('logo', models.ImageField(blank=True, help_text='Logo principal du site', upload_to='site/', verbose_name='Logo du site')),
                ('couleur_primaire', models.CharField(default='#e1306c', help_text='Code hexadécimal (ex: #e1306c)', max_length=7, verbose_name='Couleur primaire')),
                ('google_analytics', models.CharField(blank=True, help_text='Ex: G-XXXXXXXXXX', max_length=20, verbose_name='Google Analytics ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforme', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Plateforme')),
                ('url', models.URLField(verbose_name='URL du profil')),
                ('nom_affichage', models.CharField(help_text='Ex: @marlandniceme', max_length=100, verbose_name="Nom d'affichage")),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('sidebar_contact', models.BooleanField(default=False, help_text='Afficher dans la sidebar de contact flottante', verbose_name='Afficher dans le contact fixe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lien social',
                'verbose_name_plural': 'Liens sociaux',
                'ordering': ['ordre_affichage', 'plateforme'],
                'unique_together': {('plateforme',)},
            },
        ),
    ]
